DELETE http://localhost:3001/api/bookings/6
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImtvZGVyb3lAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTczODc4MjczOH0.qt1asdJ-TEf20PErJ-j5r71ajXcGfBHjR1sJDJQP8Ns

